name: Deploy Digital Garden to Coreserver

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Static HTML
        run: npm run build

      - name: Deploy via FTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: ftp
          remote-host: ${{ secrets.FTP_HOST }}
          remote-port: 21
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASS }}
          local-path: ./out/
          remote-path: /public_html/2t8.net/yusquid/
          sync: true
          ftp-mirror-options: '-R'
